name: Build

on:
  create:
    branches: 
      - release/**
    tags:
      - 'v*'
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '8.0.x' ]
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'pansynchro.sln'
      PANSQL: 'PanSQL/Pansynchro.PanSQL.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Test env
      run: env
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: 'latest'

    - name: Restore dependencies
      uses: nick-fields/retry@v2.8.3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: nuget restore $env:SOLUTION

    - name: Restore PanSQL dependencies
      uses: nick-fields/retry@v2.8.3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: nuget restore $env:PANSQL

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG --no-restore

    - name: Build2
      run: dotnet build $env:PANSQL --configuration $env:BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
